# Generated by Django 3.2.2 on 2021-05-09 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(verbose_name='Gesamtsumme')),
                ('total_weight', models.FloatField(verbose_name='Gesamtgewicht')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(verbose_name='Gesamtsumme')),
                ('total_weight', models.FloatField(verbose_name='Gesamtgewicht')),
                ('fullfilled', models.BooleanField(default=False, verbose_name='Ausgeliefert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasketElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Menge')),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.basket')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.shippingquantity')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
            ],
        ),
    ]
