# Generated by Django 3.2.2 on 2021-05-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='total_amount',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='basketelement',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Gesamtsumme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basketelement',
            name='total_weight',
            field=models.FloatField(default=0, verbose_name='Gesamtgewicht'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basketelement',
            name='amount',
            field=models.IntegerField(verbose_name='Bestellmenge'),
        ),
    ]
